### ISSUE TITLE
type = google results in error

### ISSUE THREAD

**Issue by jeestirlingdev** [40fingers/AddToCalendarHandler#6]
I have been trying out the handler on a DNN9.6.2 instance and the links work fine for type=ical, but when I try type=google I get the error

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
at the URL /DesktopModules/40Fingers/AddToCalendarHandler/google

**Comment by skamphuis** [comment]
Hi, sorry about that. It looks like I messed up by uploading the wrong package. If you download and install 0.9 again (and choose repair) it should work.

**Comment by jeestirlingdev** [comment]
Perfect. I have applied the fix and everything now works.

**Comment by Timo-Breumelhof** [comment]
@jeestirlingdev we found another issue
https://github.com/40fingers/AddToCalendarHandler/issues/7
please download the 01.00.00 version :-)
